import { Link } from 'react-router-dom'
import Icon from '../components/Icon'
import CTASection from '../components/CTASection'
import { practiceAreas } from '../data/practiceAreas'

export default function Home() { return <>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span /> Asesoría y defensa jurídica</p><h1>Defensa jurídica con <em>estrategia,</em> criterio y compromiso.</h1><p className="lead">Asesoría y representación en Derecho Penal, Derecho Penal Económico y Derecho Tributario, con una atención personalizada y un enfoque estratégico para cada caso.</p><div className="actions"><Link className="button button--primary" to="/contacto">Agendar una consulta <Icon name="arrow" /></Link><Link className="text-link" to="/servicios">Conocer mis servicios <Icon name="arrow" /></Link></div><p className="hero-note"><span /> Quito <b>·</b> Atención presencial y virtual</p></div><Portrait /></div><div className="hero-rule container"><span>Deslice para conocer</span><i /></div></section>
  <section className="about section home-about"><div className="container preview-grid"><div><p className="eyebrow"><span /> Sobre mí</p><h2>Una práctica guiada por el análisis, la estrategia y el <em>criterio.</em></h2></div><div><p>Carolina Álvarez es abogada con formación de posgrado en Derecho Penal, Derecho Penal Económico y Tributación. Su trayectoria combina experiencia en el sector público con la defensa jurídica de personas y organizaciones en asuntos que requieren análisis, estrategia y actuación responsable.</p><Link className="text-link" to="/sobre-mi">Conocer mi trayectoria <Icon name="arrow" /></Link></div></div></section>
  <section className="credentials"><div className="container"><p>Formación especializada</p><div>Derecho Penal <b>·</b> Derecho Penal Económico <b>·</b> Tributación</div></div></section>
  <section className="services section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span /> Áreas de práctica</p><h2>Servicios con una mirada <em>precisa.</em></h2></div><Link className="text-link desktop-link" to="/servicios">Ver todas las áreas <Icon name="arrow" /></Link></div><div className="services-list services-list--preview">{practiceAreas.map(area => <article className="service" key={area.number}><div className="service-number">{area.number}</div><div className="service-content"><h3>{area.title}</h3><p>{area.summary}</p></div><Link to="/servicios" className="service-link">Ver servicio <Icon name="arrow" /></Link></article>)}</div><Link className="text-link mobile-link" to="/servicios">Ver todas las áreas <Icon name="arrow" /></Link></div></section>
  <section className="method section"><div className="container"><div className="method-heading"><p className="eyebrow"><span /> Cómo trabajo</p><h2>Un acompañamiento claro<br />en <em>cada etapa.</em></h2></div><div className="steps">{[['01','Escuchar y comprender','Cada caso parte de conocer el contexto, las necesidades y los riesgos involucrados.'],['02','Analizar y definir estrategia','Se evalúan las alternativas jurídicas para establecer el camino más adecuado.'],['03','Acompañar y actuar','Comunicación cercana y seguimiento durante cada etapa del proceso.']].map(([n,title,text]) => <article className="step" key={n}><span>{n}</span><i /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><CTASection />
</> }
function Portrait() { return <figure className="portrait-wrap"><img src="/images/carolina_4.webp" alt="Carolina Álvarez, abogada" /><figcaption className="portrait-caption"><span>Carolina Álvarez</span><small>ABOGADA · ECUADOR</small></figcaption></figure> }
